[global]
address = "0.0.0.0"
port = 3000

[production]
template_dir = "assets/templates/"

[development.databases]
drop_db = { url = "postgres://postgres:memedrop@localhost/memedrop" }

[production.databases]
drop_db = { url = "postgres://postgres:memedrop@db/memedrop" }
